
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package parser;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INPUT = 10;
  public static final int openBracket = 20;
  public static final int SAVE = 19;
  public static final int DESC = 9;
  public static final int SOURCE = 13;
  public static final int RBRACE = 3;
  public static final int TRIGGER = 15;
  public static final int EQUAL = 6;
  public static final int CLICKABLE = 11;
  public static final int COLON = 4;
  public static final int LBRACE = 2;
  public static final int ID = 22;
  public static final int COMMA = 5;
  public static final int NUMBER = 23;
  public static final int EOF = 0;
  public static final int SYSTEM = 7;
  public static final int DOT = 18;
  public static final int error = 1;
  public static final int DEST = 14;
  public static final int ACTI = 17;
  public static final int STATE = 8;
  public static final int closeBracket = 21;
  public static final int GUARD = 16;
  public static final int TRANSITION = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "LBRACE",
  "RBRACE",
  "COLON",
  "COMMA",
  "EQUAL",
  "SYSTEM",
  "STATE",
  "DESC",
  "INPUT",
  "CLICKABLE",
  "TRANSITION",
  "SOURCE",
  "DEST",
  "TRIGGER",
  "GUARD",
  "ACTI",
  "DOT",
  "SAVE",
  "openBracket",
  "closeBracket",
  "ID",
  "NUMBER"
  };
}

